server:
  port: 8830
  session-timeout: 60

spring:
    redis:
       database: 0
       host: 10.6.5.42
       port: 6379
       password:
       timeout: 0
       pool:
           max-active: 8
           max-wait: -1
           max-idle: 8
           min-idle: 0
    session:
      store-type: none



