#server:
#  port: 8888
#
#eureka:
#  client:
#    serviceUrl:
#      defaultzZone: http://localhost:8888/eureka/
#    register-with-eureka: false
#    fetch-registry: false

#server:
#  port: 8000
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    serviceUrl:
#      defaultZone: http://localhost:${server.port}/eureka/


security:
  basic:
    enabled: true
  user:
    name: user # login username
    password: password

server:
  port: 8802

eureka:
  instance:
    hostname: peer2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://user:password@peer1:8801/eureka/
spring:
  application:
    name: eureka-demo1
